# Generated by Django 4.0.3 on 2022-04-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
