# Generated by Django 4.0.3 on 2022-04-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='in_work_space',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='node',
            name='memo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
